# Change these first
owner: adamus1red # Your GitHub organization or username, where this repository lives
repo: status-checks # The name of this repository

sites:
  - name: Octal
    url: https://octal.xyz
  - name: Huginn
    url: https://huginn.octal.xyz/
  - name: Health Checker
    url: https://health.octal.xyz/
  - name: Status Page
    url: https://status.spacespacespacetime.dev/
  - name: IRC
    check: "tcp-ping"
    url: $SECRET_SITE_IRC
    port: 6667
  - name: IRC SSL
    check: "tcp-ping"
    url: $SECRET_SITE_IRC
    port: 6697
  - name: ZNC
    check: "tcp-ping"
    url: $SECRET_SITE_ZNC
    port: $SECRET_SITE_ZNC_PORT
  - name: Google DNS 1
    check: "tcp-ping"
    url: 8.8.4.4
    port: 53
  - name: Google DNS 2
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.spacespacespacetime.dev 
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: night
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
