name: Maintainance Test
description: File a bug report
title: "[Maintainance]: "
labels: ["maintainance"]
assignees:
  - octocat
body:
  - type: markdown
    attributes: |
      "## Start Date
      When will the maintainance window start?
      Example `start: 2021-12-24T00:00:00.220Z`
      ## Stop Date
      When will the maintainance window start?
      Example `stop: 2021-12-24T00:00:00.220Z`
      ## Expected Outage
      What monitored services will be offline?
      Example `expectedDown: huginn`"
    validations:
      required: true

  - type: textarea
    id: machineReadable
    attributes:
      label: Details for Maintainance Window
      value: |
        <!--
        start: 2021-12-24T13:00:00.220Z
        end: 2021-12-27T00:00:00.220Z
        expectedDown: huginn
        -->
  - type: textarea
    id: longDescription
    attributes:
      label: Human Readable/Understandable reason.
      description: Also tell us, who/what/when/where/why for people to understand?
      placeholder: Tell us what you see!
      value: "Servers need a break"
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true


        

      
      
      
      
